# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PhotovoltaicsLP
                                 A QGIS plugin
 Wyznaczanie lokalizacji pod farmy fotowoltaiczne LP
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-09-04
        copyright            : (C) 2025 by EnviroSolutions Sp. z o. o.
        email                : office@envirosolutions.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import sys

plugin_libs_path = os.path.join(os.path.dirname(__file__), 'libs')
for file in os.listdir(plugin_libs_path):
    if file.endswith('.whl'):
        sys.path.append(os.path.join(plugin_libs_path, file))

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PhotovoltaicsLP class from file PhotovoltaicsLP.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .photovoltaics_LP import PhotovoltaicsLP
    return PhotovoltaicsLP(iface)
