# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PhotovoltaicsLP
                                 A QGIS plugin
 Wyznaczanie lokalizacji pod farmy fotowoltaiczne LP
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-09-04
        git sha              : $Format:%H$
        copyright            : (C) 2025 by EnviroSolutions Sp. z o. o.
        email                : office@envirosolutions.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QTimer
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QToolBar, QApplication, QMessageBox, QDialog, QComboBox
from qgis.PyQt import uic

# Initialize Qt resources from file resources.py
# resources.py is imported in initGui to avoid blocking startup
import os.path
from . import PLUGIN_NAME, PLUGIN_VERSION
from qgis.gui import *
from qgis.core import *
from .utils import Utils
from .qgis_feed import QgisFeed, QgisFeedDialog

class PhotovoltaicsLP:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        self.settings = QgsSettings() 

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # Declare instance attributes
        self.actions = []
        self.menu = u'&EnviroSolutions'
        self.toolbar = None
        self.dlg = None
        self.first_start = True

        # initialize locale
        user_locale = self.settings.value('locale/userLocale', 'pl')
        if not user_locale or not isinstance(user_locale, str):
            user_locale = 'pl'
        locale = user_locale[0:2]
        
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'PhotovoltaicsLP_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)
  

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('PhotovoltaicsLP', message)
    
   


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        # Initialize Qt resources from file resources.py
        from . import resources

        # Inicjalizacja paska narzędzi i menu (bezpieczniej w initGui)
        if not self.toolbar:
            self.toolbar = self.iface.mainWindow().findChild(QToolBar, 'EnviroSolutions')
            if not self.toolbar:
                self.toolbar = self.iface.addToolBar(u'EnviroSolutions')
                self.toolbar.setObjectName(u'EnviroSolutions')

        icon_path = ':/plugins/photovoltaics_LP/icons/fotowoltaika.svg'
        self.add_action(
            icon_path,
            text=self.tr(u'Fotowoltaika LP'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # Inicjalizacja feedu z opóźnieniem, aby nie blokować startu QGIS
        if Qgis.QGIS_VERSION_INT >= 31000:
            QTimer.singleShot(1000, self.initFeedDelayed)

    def initFeedDelayed(self):
        """Metoda wywoływana z opóźnieniem do inicjalizacji kanalu informacyjnego."""
        try:
            self.selected_industry = self.settings.value("selected_industry", None)
            show_dialog = self.settings.value("showDialog", True, type=bool)

            if self.selected_industry is None and show_dialog:
                # Tylko jeśli mamy dostęp do okna głównego
                if self.iface.mainWindow():
                    self.showBranchSelectionDialog()

            select_indust_session = self.settings.value('selected_industry')
            if select_indust_session:
                self.feed = QgisFeed(selected_industry=select_indust_session, plugin_name=PLUGIN_NAME)
                self.feed.initFeed()
        except Exception as e:
            Utils.pushLogWarning(f"Nie udało się zainicjować kanału informacyjnego: {e}")

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""


        for action in self.actions:
                self.iface.removePluginMenu(
                    u'&EnviroSolutions',
                    action)
                # self.iface.removeToolBarIcon(action)
                self.toolbar.removeAction(action)
            # remove the toolbar
        del self.toolbar


    def run(self):
        """Run method that performs all the real work"""

        # Leniwa inicjalizacja dialogu - dopiero przy pierwszym uruchomieniu przez użytkownika
        if self.dlg is None:
            from .photovoltaics_LP_dialog import PhotovoltaicsLPDialog
            self.dlg = PhotovoltaicsLPDialog()
            self.dlg.setWindowTitle('%s %s' % (PLUGIN_NAME, PLUGIN_VERSION))
            if hasattr(self.dlg, 'lbl_pluginVersion'):
                self.dlg.lbl_pluginVersion.setText('%s %s' % (PLUGIN_NAME, PLUGIN_VERSION))

        if self.first_start == True:
            self.first_start = False

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def showBranchSelectionDialog(self):
        self.qgisfeed_dialog = QgisFeedDialog()

        if self.qgisfeed_dialog.exec() == QDialog.Accepted:
            self.selected_branch = self.qgisfeed_dialog.comboBox.currentText()
            
            #Zapis w QGIS3.ini
            self.settings.setValue("selected_industry", self.selected_branch)  
            self.settings.setValue("showDialog", False)
